// Codegen: emits the app-runtime theme registry from the engine catalog.
//   npm run covers:gen
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { COVER_THEMES } from './catalog';

const out = join(__dirname, '..', '..', 'src', 'lib', 'coverThemes.gen.ts');

const header = `// GENERATED by covers-engine (npm run covers:gen) — do not edit by hand.
// Source of truth: covers-engine/src/catalog.ts
/* eslint-disable */
export type ParticleProfile =
  | 'none' | 'snow' | 'stars' | 'petals' | 'bubbles' | 'embers' | 'aurora'
  | 'confetti' | 'rain' | 'steam' | 'fireflies' | 'sparkle';

export interface CoverTheme {
  icon: string;
  accent: string;
  gradient: [string, string];
  particles: ParticleProfile;
  particleColors: string[];
  androidBg: string;
}

export const COVER_THEMES: Record<string, CoverTheme> = `;

const record = Object.fromEntries(COVER_THEMES.map((t) => [t.icon, t]));
writeFileSync(out, header + JSON.stringify(record, null, 2) + ';\n');
console.log('wrote', out, `(${COVER_THEMES.length} themes)`);
