// GENERATED by covers-engine (npm run covers:gen) — do not edit by hand.
// Source of truth: covers-engine/src/catalog.ts
/* eslint-disable */
export type ParticleProfile =
  | 'none' | 'snow' | 'stars' | 'petals' | 'bubbles' | 'embers' | 'aurora'
  | 'confetti' | 'rain' | 'steam' | 'fireflies' | 'sparkle';

export interface CoverTheme {
  icon: string;
  accent: string;
  gradient: [string, string];
  particles: ParticleProfile;
  particleColors: string[];
  androidBg: string;
}

export const COVER_THEMES: Record<string, CoverTheme> = {
  "Classic": {
    "icon": "Classic",
    "accent": "#FF6B9A",
    "gradient": [
      "#FF6B9A",
      "#9B7CFF"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#14213D"
  },
  "Midnight": {
    "icon": "Midnight",
    "accent": "#9B7CFF",
    "gradient": [
      "#1B2C5C",
      "#0E1837"
    ],
    "particles": "stars",
    "particleColors": [
      "#FFFFFF",
      "#9B7CFF"
    ],
    "androidBg": "#0E1837"
  },
  "Pearl": {
    "icon": "Pearl",
    "accent": "#24D1C3",
    "gradient": [
      "#F4F6FB",
      "#D9E2EF"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#E9EDF5"
  },
  "Earth": {
    "icon": "Earth",
    "accent": "#5BA860",
    "gradient": [
      "#8CC9E8",
      "#2E7D4F"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#2E7D4F"
  },
  "Sunset": {
    "icon": "Sunset",
    "accent": "#FFB84D",
    "gradient": [
      "#FF9E6B",
      "#7A3A55"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#FFE9B8"
    ],
    "androidBg": "#7A3A55"
  },
  "Ocean": {
    "icon": "Ocean",
    "accent": "#4DA6FF",
    "gradient": [
      "#63B7E6",
      "#0E4E7E"
    ],
    "particles": "bubbles",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#0E4E7E"
  },
  "Sakura": {
    "icon": "Sakura",
    "accent": "#FF8FB3",
    "gradient": [
      "#FFD7E4",
      "#B4638C"
    ],
    "particles": "petals",
    "particleColors": [
      "#FFC2D6",
      "#FF8FB3"
    ],
    "androidBg": "#B4638C"
  },
  "Tropical": {
    "icon": "Tropical",
    "accent": "#24D1C3",
    "gradient": [
      "#39C9B8",
      "#0E6E63"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#0E6E63"
  },
  "Winter": {
    "icon": "Winter",
    "accent": "#8FC3E4",
    "gradient": [
      "#C9DEF0",
      "#5E86AD"
    ],
    "particles": "snow",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#5E86AD"
  },
  "Coffee": {
    "icon": "Coffee",
    "accent": "#B4794A",
    "gradient": [
      "#D9A468",
      "#5C3A22"
    ],
    "particles": "steam",
    "particleColors": [
      "#FFF4E6"
    ],
    "androidBg": "#5C3A22"
  },
  "Aurora": {
    "icon": "Aurora",
    "accent": "#4BE3B2",
    "gradient": [
      "#0E2547",
      "#164B3E"
    ],
    "particles": "aurora",
    "particleColors": [
      "#4BE3B2",
      "#9B7CFF"
    ],
    "androidBg": "#0E2547"
  },
  "FrequentFlyer": {
    "icon": "FrequentFlyer",
    "accent": "#4DA6FF",
    "gradient": [
      "#8CC9E8",
      "#2C5C8F"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#2C5C8F"
  },
  "Luxury": {
    "icon": "Luxury",
    "accent": "#F0C25C",
    "gradient": [
      "#2A2138",
      "#0F0B18"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#F0C25C"
    ],
    "androidBg": "#0F0B18"
  },
  "Neon": {
    "icon": "Neon",
    "accent": "#FF4F8B",
    "gradient": [
      "#2B0F45",
      "#0E0620"
    ],
    "particles": "embers",
    "particleColors": [
      "#FF4F8B",
      "#35B5F5"
    ],
    "androidBg": "#0E0620"
  },
  "Christmas": {
    "icon": "Christmas",
    "accent": "#E4574C",
    "gradient": [
      "#12304A",
      "#071624"
    ],
    "particles": "snow",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#071624"
  },
  "CandyCane": {
    "icon": "CandyCane",
    "accent": "#DE2B40",
    "gradient": [
      "#FFF4F4",
      "#E8B8BE"
    ],
    "particles": "snow",
    "particleColors": [
      "#FFFFFF",
      "#FFD2D8"
    ],
    "androidBg": "#B22735"
  },
  "CozyWinter": {
    "icon": "CozyWinter",
    "accent": "#FFB84D",
    "gradient": [
      "#27436B",
      "#0F2036"
    ],
    "particles": "snow",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#0F2036"
  },
  "Halloween": {
    "icon": "Halloween",
    "accent": "#FF8C42",
    "gradient": [
      "#2A1C4F",
      "#120A26"
    ],
    "particles": "embers",
    "particleColors": [
      "#FF8C42"
    ],
    "androidBg": "#120A26"
  },
  "Ghost": {
    "icon": "Ghost",
    "accent": "#C445E0",
    "gradient": [
      "#3A2260",
      "#170D30"
    ],
    "particles": "fireflies",
    "particleColors": [
      "#C4B5F0"
    ],
    "androidBg": "#170D30"
  },
  "WitchingHour": {
    "icon": "WitchingHour",
    "accent": "#9B7CFF",
    "gradient": [
      "#241547",
      "#0D0722"
    ],
    "particles": "stars",
    "particleColors": [
      "#C4B5F0",
      "#FFB84D"
    ],
    "androidBg": "#0D0722"
  },
  "Pride": {
    "icon": "Pride",
    "accent": "#FF6B9A",
    "gradient": [
      "#E4574C",
      "#7C4DBF"
    ],
    "particles": "confetti",
    "particleColors": [
      "#E4574C",
      "#FFB84D",
      "#F5D547",
      "#4C9F70",
      "#4DA6FF",
      "#9B7CFF"
    ],
    "androidBg": "#7C4DBF"
  },
  "PrideNeon": {
    "icon": "PrideNeon",
    "accent": "#FF4F8B",
    "gradient": [
      "#1B0F35",
      "#0A0518"
    ],
    "particles": "confetti",
    "particleColors": [
      "#FF4F8B",
      "#FFB84D",
      "#4BE3B2",
      "#35B5F5",
      "#C445E0"
    ],
    "androidBg": "#0A0518"
  },
  "PrideNight": {
    "icon": "PrideNight",
    "accent": "#9B7CFF",
    "gradient": [
      "#1B2C5C",
      "#0E1837"
    ],
    "particles": "stars",
    "particleColors": [
      "#FFB84D",
      "#4BE3B2",
      "#FF6B9A"
    ],
    "androidBg": "#0E1837"
  },
  "Metropolis": {
    "icon": "Metropolis",
    "accent": "#FFB84D",
    "gradient": [
      "#2E3B77",
      "#E88A6A"
    ],
    "particles": "stars",
    "particleColors": [
      "#FFC97E",
      "#FFFFFF"
    ],
    "androidBg": "#141F49"
  },
  "VintageVoyage": {
    "icon": "VintageVoyage",
    "accent": "#B4543E",
    "gradient": [
      "#E3CD9F",
      "#B29360"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#B29360"
  },
  "Summit": {
    "icon": "Summit",
    "accent": "#4DA6FF",
    "gradient": [
      "#3A5787",
      "#FFD9C2"
    ],
    "particles": "snow",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#16294F"
  },
  "Oasis": {
    "icon": "Oasis",
    "accent": "#F5A66B",
    "gradient": [
      "#F5A66B",
      "#7A3A55"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#FFE9B8"
    ],
    "androidBg": "#7A3A55"
  },
  "Linen": {
    "icon": "Linen",
    "accent": "#C4552F",
    "gradient": [
      "#F4EEE0",
      "#DCCFB2"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#DCCFB2"
  },
  "Explorer": {
    "icon": "Explorer",
    "accent": "#24D1C3",
    "gradient": [
      "#155E5A",
      "#0C2A2E"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#0C2A2E"
  },
  "Spring": {
    "icon": "Spring",
    "accent": "#FF8FB3",
    "gradient": [
      "#BFE8F2",
      "#A6D48A"
    ],
    "particles": "petals",
    "particleColors": [
      "#FFD7E4",
      "#FFFFFF"
    ],
    "androidBg": "#A6D48A"
  },
  "Summer": {
    "icon": "Summer",
    "accent": "#FFB84D",
    "gradient": [
      "#37C0E8",
      "#F4C56B"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#37C0E8"
  },
  "Autumn": {
    "icon": "Autumn",
    "accent": "#DC7A3C",
    "gradient": [
      "#F0B25A",
      "#8C3A24"
    ],
    "particles": "petals",
    "particleColors": [
      "#E8912F",
      "#D2542B",
      "#F2B84B"
    ],
    "androidBg": "#8C3A24"
  },
  "LunarNewYear": {
    "icon": "LunarNewYear",
    "accent": "#F3CE6A",
    "gradient": [
      "#C4222A",
      "#5E0E14"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#F3D27A"
    ],
    "androidBg": "#5E0E14"
  },
  "Gold": {
    "icon": "Gold",
    "accent": "#F0C25C",
    "gradient": [
      "#2A2418",
      "#0B0F1C"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#F0C25C"
    ],
    "androidBg": "#0B0F1C"
  },
  "Marble": {
    "icon": "Marble",
    "accent": "#B08D2E",
    "gradient": [
      "#FBFAF6",
      "#DEDBD1"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#DEDBD1"
  },
  "Galaxy": {
    "icon": "Galaxy",
    "accent": "#9B7CFF",
    "gradient": [
      "#2A1A54",
      "#080512"
    ],
    "particles": "stars",
    "particleColors": [
      "#FFFFFF",
      "#9B7CFF"
    ],
    "androidBg": "#080512"
  },
  "ArtDeco": {
    "icon": "ArtDeco",
    "accent": "#D9B45A",
    "gradient": [
      "#123049",
      "#08131F"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#D9B45A"
    ],
    "androidBg": "#08131F"
  },
  "Nordic": {
    "icon": "Nordic",
    "accent": "#4DA6FF",
    "gradient": [
      "#3E6E92",
      "#E7C9B0"
    ],
    "particles": "snow",
    "particleColors": [
      "#FFFFFF"
    ],
    "androidBg": "#1B3A5C"
  },
  "Safari": {
    "icon": "Safari",
    "accent": "#E88A3C",
    "gradient": [
      "#F4C05A",
      "#7A3524"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#7A3524"
  },
  "Mediterranean": {
    "icon": "Mediterranean",
    "accent": "#2E9BD6",
    "gradient": [
      "#2E9BD6",
      "#BFE6F2"
    ],
    "particles": "none",
    "particleColors": [],
    "androidBg": "#2E9BD6"
  },
  "EveryContinent": {
    "icon": "EveryContinent",
    "accent": "#FFD36B",
    "gradient": [
      "#123A6B",
      "#060D1F"
    ],
    "particles": "stars",
    "particleColors": [
      "#FFFFFF",
      "#FFD36B"
    ],
    "androidBg": "#060D1F"
  },
  "WorldlyLegend": {
    "icon": "WorldlyLegend",
    "accent": "#E8C25A",
    "gradient": [
      "#231B08",
      "#050301"
    ],
    "particles": "sparkle",
    "particleColors": [
      "#E8C25A"
    ],
    "androidBg": "#050301"
  }
};
