// AUTO-GENERATED by scripts/build-hero-luminance.mjs-equivalent (Pillow).
// Codes whose destination photo is DARK across the top strip (where the Story
// hero wordmark sits), so the logo should render in white there; every other
// code reads better with the navy wordmark. Regenerate if the /destinations
// imagery changes.
export const HERO_TOP_DARK = new Set<string>([
  'AF', 'AG', 'AL', 'AM', 'AO', 'AS', 'BB', 'BD', 'BF', 'BG', 'BI', 'BJ', 'BM', 'BN', 'BS', 'BW',
  'BY', 'BZ', 'CD', 'CF', 'CG', 'CH', 'CK', 'CM', 'CU', 'CY', 'DM', 'DO', 'DZ', 'FK', 'FM', 'FO',
  'FR', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GQ', 'GU', 'GY', 'HK', 'HU', 'IL', 'IQ',
  'IS', 'JO', 'JP', 'KG', 'KH', 'KM', 'KR', 'KW', 'LI', 'LK', 'LS', 'LT', 'LY', 'MA', 'MD', 'ME',
  'MG', 'MH', 'ML', 'MN', 'MR', 'MU', 'MV', 'MY', 'MZ', 'NA', 'NC', 'NO', 'OM', 'PA', 'PH', 'PL',
  'PS', 'RU', 'SA', 'SB', 'SD', 'SE', 'SG', 'SN', 'SO', 'SY', 'TD', 'TG', 'TJ', 'TL', 'TT', 'TV',
  'UZ', 'VA', 'VC', 'VU', 'YE', 'ZM', 'ZW',
]);

/** True when the Story hero logo should be white (dark image), else navy. */
export function heroLogoIsWhite(code?: string): boolean {
  return !!code && HERO_TOP_DARK.has(code);
}
